"""them pos

Revision ID: f16b30957739
Revises: 
Create Date: 2025-03-19 11:47:49.957296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16b30957739'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nhanvien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pos', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nhanvien', schema=None) as batch_op:
        batch_op.drop_column('pos')

    # ### end Alembic commands ###
